=== hervesiyou/MESDEVELOPPEMENTS/XSD/accounts.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
    <xs:include schemaLocation="iuser.xsd"/><xs:include schemaLocation="igroup.xsd"/><xs:include schemaLocation="role.xsd"/><xs:element name="accounts" type="accountsType"/>
    <xs:complexType name="substituteType">
        <xs:annotation>
            <xs:documentation>Reference a substitute</xs:documentation>
        </xs:annotation>
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="reference" use="required">
                    <xs:annotation>
                        <xs:documentation>User login identifier</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="groupRefType">
        <xs:annotation>
            <xs:documentation>
                Reference to a parent group
            </xs:documentation>
        </xs:annotation>
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="referenceType" name="reference" use="required">
                    <xs:annotation>
                        <xs:documentation>Group reference identifier</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="groupsRefType">
        <xs:annotation>
            <xs:documentation>
                Parent group list references
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element type="groupRefType" name="parentGroup" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:boolean" name="reset" default="false" use="optional">
            <xs:annotation>
                <xs:documentation>
                    If true, only referenced groups are parents of account, previously parents links are removed.
                    If false, parent groups are added, currents group links are preserved.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
    <xs:complexType name="statusType">
        <xs:annotation>
            <xs:documentation>
                If status is false, the user cannot be logged to system.
            </xs:documentation>
        </xs:annotation>
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:boolean" name="activated" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="passwordType">
        <xs:annotation>
            <xs:documentation>Password for user account</xs:documentation>
        </xs:annotation>
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:boolean" name="crypted" use="required">
                    <xs:annotation>
                        <xs:documentation>
                            Set to false to record a new clear password. Only crypted password is recorded
                            and can be exported
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="rolesRefType">
        <xs:annotation>
            <xs:documentation>Associated roles for an account</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element type="roleRefType" name="associatedRole" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:boolean" name="reset" default="false" use="optional">
            <xs:annotation>
                <xs:documentation>
                    If true, only listed roles are references, currents roles are removed.
                    If false, roles are added, currents roles are not removed
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
    <xs:complexType name="documentType">
        <xs:annotation>
            <xs:documentation>Associated document of the account</xs:documentation>
        </xs:annotation>
        <xs:sequence>
        <xs:element type="family-iuser-type" name="iuser" minOccurs="0"/><xs:element type="family-igroup-type" name="igroup" minOccurs="0"/><xs:element type="family-role-type" name="role" minOccurs="0"/></xs:sequence>
        <xs:attribute type="referenceType" name="family" use="optional">
            <xs:annotation>
                <xs:documentation>Associated document family</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
    <xs:complexType name="accountsType">
        <xs:sequence>
            <xs:element type="rolesType" name="roles" minOccurs="0"/>
            <xs:element type="groupsType" name="groups" minOccurs="0"/>
            <xs:element type="usersType" name="users" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="date" use="optional"/>
    </xs:complexType>
    <xs:complexType name="usersType">
        <xs:sequence>
            <xs:element type="userType" name="user" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="userType">
        <xs:all>
            <xs:element type="referenceType" name="login">
                <xs:annotation>
                    <xs:documentation>User connexion identifier</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:string" name="firstname" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>User first name</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:string" name="lastname">
                <xs:annotation>
                    <xs:documentation>User last name</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:string" name="mail" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>User mail address</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="statusType" name="status" minOccurs="0"/>
            <xs:element type="substituteType" name="substitute" minOccurs="0"/>
            <xs:element type="rolesRefType" name="associatedRoles" minOccurs="0"/>
            <xs:element type="groupsRefType" name="parentGroups" minOccurs="0"/>
            <xs:element type="passwordType" name="password" minOccurs="0"/>
            <xs:element type="documentType" name="document" minOccurs="0"/>
        </xs:all>
        <xs:attribute type="idType" name="id" use="optional"/>
    </xs:complexType>
    <xs:complexType name="roleRefType">
        <xs:annotation>
            <xs:documentation>Reference to a role</xs:documentation>
        </xs:annotation>
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="referenceType" name="reference" use="required">
                    <xs:annotation>
                        <xs:documentation>Role reference identifier</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>


    <xs:complexType name="groupType">
        <xs:sequence>
            <xs:element type="referenceType" name="reference"/>
            <xs:element name="displayName" type="xs:string"/>
            <xs:element type="rolesRefType" name="associatedRoles" minOccurs="0"/>
            <xs:element type="groupsRefType" name="parentGroups" minOccurs="0"/>
            <xs:element type="documentType" name="document" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="idType" name="id" use="optional"/>
    </xs:complexType>
    <xs:complexType name="groupsType">
        <xs:sequence>
            <xs:element type="groupType" name="group" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="rolesType">
        <xs:annotation>
            <xs:documentation>Role list</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element type="roleType" name="role" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>

    </xs:complexType>

    <xs:complexType name="roleType">
        <xs:annotation>
            <xs:documentation>Role definition to be referenced by group or user</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element type="referenceType" name="reference"/>
            <xs:element type="xs:string" name="displayName"/>
            <xs:element type="documentType" name="document" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="idType" name="id" use="optional"/>
    </xs:complexType>

    <xs:simpleType name="referenceType">
        <xs:annotation>
            <xs:documentation>Unique reference for an account</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:normalizedString">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>


    <xs:simpleType name="idType">
        <xs:annotation>
            <xs:documentation>System reference for an account - not used when import accounts</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:nonNegativeInteger"/>
    </xs:simpleType>

</xs:schema>

=== hervesiyou/MESDEVELOPPEMENTS/GEDMINJUSTICEAPP/accounts.xml
<?xml version="1.0" encoding="utf-8"?>
<accounts date="2017-03-20T10:09:50" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../XSD/accounts.xsd">
  <roles>
			<role id="43">
			  <reference>role_visiteurs</reference>
			  <displayName>VisiteurRole</displayName>
			  <document family="ROLE">
				<role title="Visiteur de la GED" revision="0" modification-date="2017-03-20T09:59:44" version="" state=""/>
			  </document>
			</role>
			<role>
						<reference>role_membres</reference>
						<displayName>MembreRole</displayName>
						<document family="ROLE">
						  <role title="Membre de la GED MINJUSTICE(Membre de la GED)"/>
						</document>
			</role>
			<role>
						<reference>role_administrateurs</reference>
						<displayName>AdministrateurRole</displayName>
						<document family="ROLE">
						  <role title="Administrateur de la GED MINJUSTICE(Administrateur de la GED)"/>
						</document>
			</role>    
			<role>
						<reference>role_communicateurs</reference>
						<displayName>CommunicateurRole</displayName>
						<document family="ROLE">
						  <role title="Comminicateur de la GED MINJUSTICE(Publieur de Textes)"/>
						</document>
			</role> 
			<role>
						<reference>role_legislateurs</reference>
						<displayName>LegislateurRole</displayName>
						<document family="ROLE">
						  <role title="Legislateur dans la GED MINJUSTICE (Createur de Textes)"/>
						</document>
			</role> 
			<role>
						<reference>role_archiveurs</reference>
						<displayName>ArchiveurRole</displayName>
						<document family="ROLE">
						  <role title="Archiveur dans la GED MINJUSTICE(Chargeur et Sauvegardeur de Textes)"/>
						</document>
			</role> 
  
  </roles>
  <groups>
			<group id="2">
			  <reference>all</reference>
			  <displayName>Utilisateurs</displayName>
			  <document family="IGROUP">
				<igroup name="GDEFAULT" title="Utilisateurs" revision="0" modification-date="2017-03-20T10:05:53" version="" state=""/>
			  </document>
			</group>
			<group id="44">
			  <reference>visiteurgroupeid</reference>
			  <displayName>VisiteurGroupe</displayName>
			  <associatedRoles reset="false">
				<associatedRole reference="role_visiteurs"/>
			  </associatedRoles>
			  <parentGroups reset="false">
				<parentGroup reference="all"/>
			  </parentGroups>
			  <document family="IGROUP">
				<igroup title="VisiteurGroupe" revision="0" modification-date="2017-03-20T10:06:59" version="" state=""/>
			  </document>
			</group>
						 <group>
							<reference>membregroupeid</reference>
							<displayName>MembreGroupe</displayName>
							<associatedRoles reset="false">
							  <associatedRole reference="role_membres"/>
							  <associatedRole reference="role_legislateurs"/>
							</associatedRoles>
							<parentGroups reset="false">
							  <parentGroup reference="all"/>
							</parentGroups>
							<document family="IGROUP">
							  <igroup title="MembreGroupe"/>
							</document>
						 </group>
						 <group>
							<reference>administrateurgroupeid</reference>
							<displayName>AdministrateurGroupe</displayName>
							<associatedRoles reset="false">
							   <associatedRole reference="role_administrateurs"/>
							   <associatedRole reference="role_archiveurs"/>
							   <associatedRole reference="role_communicateurs"/>
							</associatedRoles>
							<parentGroups reset="false">
							  <parentGroup reference="all"/>
							</parentGroups>
							<document family="IGROUP">
							  <igroup title="AdministrateurGroupe"/>
							</document>
						 </group>
  </groups>
  <users>
    <user id="1">
      <login>admin</login>
      <firstname>Dynacase Platform</firstname>
      <lastname>Master</lastname>
      <status activated="true"/>
      <password crypted="true">$5$mC3EzGPrG8Cqg/vC$MqMq6/FKTWEo6Cdm3zaxz.a8o0IajIBEzajNiXykVBC</password>
      <parentGroups reset="false">
        <parentGroup reference="all"/>
      </parentGroups>
      <document family="IUSER">
        <iuser name="USER_ADMIN" title="Master Dynacase Platform" revision="0" modification-date="2017-03-17T20:24:51" version="" state=""/>
      </document>
    </user>
    <user id="3">
      <login>anonymous</login>
      <firstname>guest</firstname>
      <lastname>anonymous</lastname>
      <status activated="true"/>
      <password crypted="true">$5$fG9VxyOQ8hLif8nh$iXY2LBadMC1YlKBdvfSIgXSS0CuHD9Cf6FgEPO9B4eC</password>
      <document family="IUSER">
        <iuser name="USER_GUEST" title="anonymous guest" revision="0" modification-date="2017-03-17T20:24:51" version="" state=""/>
      </document>
    </user>
    <user id="45">
      <login>herve</login>
      <firstname>stephane</firstname>
      <lastname>herve</lastname>
      <mail>herve@gmail.com</mail>
      <status activated="true"/>
      <password crypted="true">$5$Jvax0r1zahsURmVQ$iwkUyJ1a9B0BFe9oja5iIZOndhnoedhwPrXl7YkMSw8</password>
      <parentGroups reset="false">
        <parentGroup reference="all"/>
        <parentGroup reference="visiteurgroupeid"/>
      </parentGroups>
      <document family="IUSER">
        <iuser title="herve stephane" revision="0" modification-date="2017-03-20T10:07:55" version="" state=""/>
      </document>
    </user>
					<user>
					  <login>yannick</login>
					  <firstname>jean</firstname>
					  <lastname>yannick</lastname>
					  <mail>yannick@gmail.com</mail>
					  <status activated="true"/>
					  <password crypted="true">$5$Jvax0r1zahsURmVQ$iwkUyJ1a9B0BFe9oja5iIZOndhnoedhwPrXl7YkMSw8</password>
					  <parentGroups reset="false">
						<parentGroup reference="all"/>
						<parentGroup reference="administrateurgroupeid"/>
					  </parentGroups>
					  <document family="IUSER">
						<iuser title="yannick jean" revision="0" modification-date="2017-03-20T10:07:55" version="" state=""/>
					  </document>
					</user>
					<user>
					  <login>simon</login>
					  <firstname>pierre</firstname>
					  <lastname>cephas</lastname>
					  <mail>simon@gmail.com</mail>
					  <status activated="true"/>
					  <password crypted="true">$5$Jvax0r1zahsURmVQ$iwkUyJ1a9B0BFe9oja5iIZOndhnoedhwPrXl7YkMSw8</password>
					  <parentGroups reset="false">
						<parentGroup reference="all"/>
						<parentGroup reference="visiteurgroupeid"/>
					  </parentGroups>
					  <document family="IUSER">
						<iuser title="Simon Cephas" revision="0" modification-date="2017-03-20T10:07:55" version="" state=""/>
					  </document>
					</user>
					<user>
					  <login>jean</login>
					  <firstname>Ebelle</firstname>
					  <lastname>Bernard</lastname>
					  <mail>jean@gmail.com</mail>
					  <status activated="true"/>
					  <password crypted="true">$5$Jvax0r1zahsURmVQ$iwkUyJ1a9B0BFe9oja5iIZOndhnoedhwPrXl7YkMSw8</password>
					  <parentGroups reset="false">
						<parentGroup reference="all"/>
						<parentGroup reference="administrateurgroupeid"/>
					  </parentGroups>
					  <document family="IUSER">
						<iuser title="Jean Ebelle" revision="0" modification-date="2017-03-20T10:07:55" version="" state=""/>
					  </document>
					</user>
					<user>
					  <login>paul</login>
					  <firstname>bile</firstname>
					  <lastname>arnold</lastname>
					  <mail>paul@gmail.com</mail>
					  <status activated="true"/>
					  <password crypted="true">$5$Jvax0r1zahsURmVQ$iwkUyJ1a9B0BFe9oja5iIZOndhnoedhwPrXl7YkMSw8</password>
					  <parentGroups reset="false">
						<parentGroup reference="all"/>
						<parentGroup reference="membregroupeid"/>
					  </parentGroups>
					  <document family="IUSER">
						<iuser title="Paul Bile" revision="0" modification-date="2017-03-20T10:07:55" version="" state=""/>
					  </document>
					</user>
					<user>
					  <login>atango</login>
					  <firstname>abraham</firstname>
					  <lastname>ondo</lastname>
					  <mail>atango@gmail.com</mail>
					  <status activated="true"/>
					  <password crypted="true">$5$Jvax0r1zahsURmVQ$iwkUyJ1a9B0BFe9oja5iIZOndhnoedhwPrXl7YkMSw8</password>
					  <parentGroups reset="false">
						<parentGroup reference="all"/>
						<parentGroup reference="membregroupeid"/>
					  </parentGroups>
					  <document family="IUSER">
						<iuser title="Atango Ondo" revision="0" modification-date="2017-03-20T10:07:55" version="" state=""/>
					  </document>
					</user>
					<user>
					  <login>souley</login>
					  <firstname>pierre</firstname>
					  <lastname>oyolo</lastname>
					  <mail>souley@gmail.com</mail>
					  <status activated="true"/>
					  <password crypted="true">$5$Jvax0r1zahsURmVQ$iwkUyJ1a9B0BFe9oja5iIZOndhnoedhwPrXl7YkMSw8</password>
					  <parentGroups reset="false">
						<parentGroup reference="all"/>
						<parentGroup reference="membregroupeid"/>
					  </parentGroups>
					  <document family="IUSER">
						<iuser title="Souley oyolo" revision="0" modification-date="2017-03-20T10:07:55" version="" state=""/>
					  </document>
					</user>
					<user>
					  <login>ndi</login>
					  <firstname>agbor</firstname>
					  <lastname>mbuh</lastname>
					  <mail>ndi@gmail.com</mail>
					  <status activated="true"/>
					  <password crypted="true">$5$Jvax0r1zahsURmVQ$iwkUyJ1a9B0BFe9oja5iIZOndhnoedhwPrXl7YkMSw8</password>
					  <parentGroups reset="false">
						<parentGroup reference="all"/>
						<parentGroup reference="administrateurgroupeid"/>
					  </parentGroups>
					  <document family="IUSER">
						<iuser title="Ndi Mbuh" revision="0" modification-date="2017-03-20T10:07:55" version="" state=""/>
					  </document>
					</user>
					<user>
					  <login>ekani</login>
					  <firstname>brice</firstname>
					  <lastname>tarzan</lastname>
					  <mail>ekani@gmail.com</mail>
					  <status activated="true"/>
					  <password crypted="true">$5$Jvax0r1zahsURmVQ$iwkUyJ1a9B0BFe9oja5iIZOndhnoedhwPrXl7YkMSw8</password>
					  <parentGroups reset="false">
						<parentGroup reference="all"/>
						<parentGroup reference="membregroupeid"/>
					  </parentGroups>
					  <document family="IUSER">
